/**
 * Config plugin for the local `oms-native` module.
 *
 * FR-84 on Android: the OS has no per-file backup flag, so the downloads
 * directory is excluded declaratively. This writes two resource files and
 * points the generated `<application>` at them:
 *
 * - `res/xml/oms_backup_rules.xml` -> `android:fullBackupContent`
 *   (Auto Backup, Android 11 and older).
 * - `res/xml/oms_data_extraction_rules.xml` -> `android:dataExtractionRules`
 *   (Android 12+, both cloud backup and device-to-device transfer).
 *
 * `domain="file"` is the app's internal files dir, which is exactly what
 * expo-file-system reports as `Paths.document` on Android
 * (FileSystemModule.kt -> appContext.persistentFilesDirectory), so the path
 * below matches `<documents>/oms-downloads/` in src/downloads/paths.ts.
 *
 * This only ever edits the app's OWN generated native project (android/app),
 * never anything inside node_modules. iOS needs no plugin work: the module is
 * autolinked and sets `isExcludedFromBackup` at runtime.
 */
const fs = require("node:fs");
const path = require("node:path");
const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withDangerousMod,
} = require("expo/config-plugins");

/** Must stay in sync with ROOT_DIR_NAME in src/downloads/paths.ts. */
const DOWNLOADS_DIR = "oms-downloads";
const BACKUP_RULES = "oms_backup_rules";
const DATA_EXTRACTION_RULES = "oms_data_extraction_rules";

const backupRulesXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by modules/oms-native/app.plugin.js - do not edit by hand. -->
<full-backup-content>
    <exclude domain="file" path="${DOWNLOADS_DIR}/" />
</full-backup-content>
`;

const dataExtractionRulesXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by modules/oms-native/app.plugin.js - do not edit by hand. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="file" path="${DOWNLOADS_DIR}/" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="file" path="${DOWNLOADS_DIR}/" />
    </device-transfer>
</data-extraction-rules>
`;

const withBackupRulesResources = (config) =>
  withDangerousMod(config, [
    "android",
    async (dangerousConfig) => {
      const xmlDir = path.join(
        dangerousConfig.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "xml",
      );
      await fs.promises.mkdir(xmlDir, { recursive: true });
      await fs.promises.writeFile(
        path.join(xmlDir, `${BACKUP_RULES}.xml`),
        backupRulesXml,
        "utf8",
      );
      await fs.promises.writeFile(
        path.join(xmlDir, `${DATA_EXTRACTION_RULES}.xml`),
        dataExtractionRulesXml,
        "utf8",
      );
      return dangerousConfig;
    },
  ]);

const withBackupRulesManifest = (config) =>
  withAndroidManifest(config, (manifestConfig) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      manifestConfig.modResults,
    );
    application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES}`;
    application.$["android:dataExtractionRules"] = `@xml/${DATA_EXTRACTION_RULES}`;
    return manifestConfig;
  });

const withOmsNative = (config) => withBackupRulesManifest(withBackupRulesResources(config));

module.exports = createRunOncePlugin(withOmsNative, "oms-native", "1.0.0");
