/**
 * Typed wrappers over the Rust cache commands.
 *
 * This is a hand-maintained MIRROR of `desktop/bindings.ts` (generated by
 * tauri-specta), for the same reason `src/desktop/tauri.ts` mirrors the media
 * commands: the app's package.json must not grow `@tauri-apps/api`, and the
 * generated file imports it. If bindings.ts changes, this file changes - and
 * because both sides are explicit, a rename shows up as a typecheck failure
 * here instead of an `invoke` that rejects at runtime on the user's machine.
 *
 * Argument names are camelCase because Tauri v2 converts them to the Rust
 * snake_case parameters; the COMMAND names stay snake_case because that is
 * what `#[tauri::command]` registers.
 *
 * Every command that Rust declares as `Result<T, String>` REJECTS on the JS
 * side. Nothing here catches: the callers decide, and most of them decide
 * that a failed cache operation is a silent no-op rather than a user-visible
 * error, because the app streams perfectly well without a cache.
 */
import type { DownloadFileStatus, DownloadKind } from "@/domain/downloads";
import type { MediaId, SongKey } from "@/domain/ids";
import { getTauriGlobals, newTauriChannel } from "@/desktop/tauri";

// ---------------------------------------------------------------------------
// Wire types (mirror of the specta exports)
// ---------------------------------------------------------------------------

/** Rust `Kind` and `FileStatus` are the same two unions the app already has,
 *  on purpose: the two halves of the app speak one vocabulary. */
export type CacheKind = DownloadKind;
export type CacheStatus = DownloadFileStatus;

export interface CacheOpenResult {
  /** false on Linux (WebKit 146351) and on any shell that failed to open. */
  available: boolean;
  origin: string;
  budgetBytes: number;
}

export interface CacheUsage {
  pinnedBytes: number;
  pinnedFiles: number;
  evictableBytes: number;
  evictableFiles: number;
}

/** A `files` row as JS sees it. No paths: the local index builds the URL. */
export interface FileEntry {
  songKey: string;
  kind: CacheKind;
  status: CacheStatus;
  mediaId: string;
  bytes: number;
  progress: number;
  predicted: boolean;
  updatedAt: number;
}

export interface OfflinePlaylistEntry {
  id: number;
  name: string;
  artworkMediaId: string | null;
  songCount: number;
  sourceExternalId: string | null;
  updatedAt: number;
}

export interface StoredLyricsEntry {
  state: string;
  json: string | null;
}

/** One request for bytes inside an explicit download. */
export interface Want {
  kind: CacheKind;
  mediaId: MediaId;
}

/**
 * What crosses the IPC boundary. Two variants and nothing else: the split
 * between them is decided in RUST (events.rs), so a three-way parallel
 * download cannot flood the boundary and the JS side cannot get the
 * two-channel discipline wrong even if it tries.
 */
export type CacheEvent =
  | {
      type: "status";
      songKey: string;
      kind: CacheKind;
      status: CacheStatus;
      progress: number;
    }
  | { type: "progress"; songKey: string; kind: CacheKind; progress: number };

// ---------------------------------------------------------------------------
// Invoke
// ---------------------------------------------------------------------------

const invoke = async <T>(command: string, args?: Record<string, unknown>): Promise<T> => {
  const tauri = getTauriGlobals();
  if (!tauri) throw new Error("Not running inside the desktop shell.");
  return (await tauri.core.invoke(command, args)) as T;
};

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------

/**
 * `api_base` and `token` are PARAMETERS, not configuration Rust reads from
 * disk: the shell never persists credentials, it only holds them in memory
 * for as long as the session lives. Without them Rust cannot build
 * `/media/:id/data?token=` and no transfer can happen at all.
 */
export const cacheOpen = (
  userId: string,
  apiBase: string,
  token: string | null,
): Promise<CacheOpenResult> => invoke("cache_open", { userId, apiBase, token });

export const cacheClose = (): Promise<void> => invoke("cache_close");

/** Token rotation. Skipping it turns every later transfer into a 404. */
export const cacheSetAuth = (apiBase: string, token: string | null): Promise<void> =>
  invoke("cache_set_auth", { apiBase, token });

/**
 * ONE long-lived channel for all status and progress. Returns false when the
 * shell is too old to expose `core.Channel`, in which case the fork installs
 * nothing rather than silently running blind.
 */
export const cacheSubscribe = async (
  onEvent: (event: CacheEvent) => void,
): Promise<boolean> => {
  const channel = newTauriChannel<CacheEvent>(onEvent);
  if (!channel) return false;
  await invoke("cache_subscribe", { onEvent: channel });
  return true;
};

// ---------------------------------------------------------------------------
// Transfers
// ---------------------------------------------------------------------------

/** Explicit download: writes the `songs` row (that row IS the pin) + wants. */
export const cacheDownload = (
  songKey: SongKey,
  songJson: string,
  wants: Want[],
): Promise<void> => invoke("cache_download", { songKey, songJson, wants });

/**
 * The predictive tier. Returns false when RUST refused - explicit transfers
 * in flight, a guess already running, the session waste ceiling reached, or a
 * jam song. The single-slot and suspension rules are enforced on that side on
 * purpose, so a bug in this bundle cannot break them.
 */
export const cachePredict = (songKey: SongKey, mediaId: MediaId): Promise<boolean> =>
  invoke("cache_predict", { songKey, mediaId });

/** Per KIND, never per song: the same song may carry an explicit download. */
export const cacheCancel = (songKey: SongKey, kind: CacheKind): Promise<void> =>
  invoke("cache_cancel", { songKey, kind });

/** The desktop `touchAndPromote`: a guess the user actually played. */
export const cachePromote = (songKey: SongKey): Promise<void> =>
  invoke("cache_promote", { songKey });

export const cacheRemoveSong = (songKey: SongKey): Promise<void> =>
  invoke("cache_remove_song", { songKey });

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/** The stored `song_json` blobs. Rust returns TEXT and never parses them:
 *  the pure derivations that filter and sort them already exist in
 *  downloads/library.ts and duplicating one in Rust would be a second truth. */
export const cacheListSongs = (): Promise<string[]> => invoke("cache_list_songs");

export const cacheListFiles = (): Promise<FileEntry[]> => invoke("cache_list_files");

export const cacheUsage = (): Promise<CacheUsage> => invoke("cache_usage");

// ---------------------------------------------------------------------------
// Collections, playlists, lyrics
// ---------------------------------------------------------------------------

export const cacheCollectionsList = (): Promise<string[]> =>
  invoke("cache_collections_list");

export const cacheCollectionsAdd = (key: string): Promise<void> =>
  invoke("cache_collections_add", { key });

export const cacheCollectionsRemove = (key: string): Promise<void> =>
  invoke("cache_collections_remove", { key });

/** Persisted membership. Without it a cold airplane-mode launch knows the
 *  playlist is downloaded but not WHICH songs it holds - the exact bug the
 *  mobile side hit before schema v4. */
export const cacheCollectionsSetSongs = (
  key: string,
  songKeys: string[],
): Promise<void> => invoke("cache_collections_set_songs", { key, songKeys });

export const cacheCollectionsSongs = (key: string): Promise<string[]> =>
  invoke("cache_collections_songs", { key });

export const cachePlaylistsList = (): Promise<OfflinePlaylistEntry[]> =>
  invoke("cache_playlists_list");

export const cachePlaylistsUpsert = (playlist: OfflinePlaylistEntry): Promise<void> =>
  invoke("cache_playlists_upsert", { playlist });

export const cachePlaylistsRemove = (id: number): Promise<void> =>
  invoke("cache_playlists_remove", { id });

export const cacheLyricsGet = (songKey: SongKey): Promise<StoredLyricsEntry | null> =>
  invoke("cache_lyrics_get", { songKey });

export const cacheLyricsSet = (
  songKey: SongKey,
  lyricsState: string,
  lyricsJson: string | null,
): Promise<void> => invoke("cache_lyrics_set", { songKey, lyricsState, lyricsJson });

export const cacheSetBudget = (bytes: number): Promise<void> =>
  invoke("cache_set_budget", { bytes });

/** Empties the evictable tier ENTIRELY. Pinned bytes are never touched:
 *  the user chose those, and "clear cache" must never delete a library. */
export const cachePurge = (): Promise<CacheUsage> => invoke("cache_purge");
