/**
 * Pure protocol layer of the desktop bridge: IPC payload parsing and the
 * playback mirror's send discipline. Deliberately import-free of player/ and
 * react-native so it is testable under plain `bun test` (same split the
 * other packages use: protocol below, wiring above).
 *
 * The wire shapes mirror desktop/bindings.ts (generated by tauri-specta from
 * the Rust side). If the Rust enum changes, regenerate the bindings and this
 * file's parser fails the new case loudly in tests instead of silently in a
 * switch.
 */

/** Copy of RemoteCommand (src/player/lockScreen.ts) minus the app-only
 * variants; kept structural so lockScreen's type accepts every value. */
export type DesktopRemoteCommand =
  | { kind: "play" }
  | { kind: "pause" }
  | { kind: "toggle" }
  | { kind: "next" }
  | { kind: "previous" }
  | { kind: "seekForward" }
  | { kind: "seekBackward" }
  | { kind: "seek"; seconds: number };

/** Slow tick while playing: keeps the platform progress bar honest. */
export const PLAYBACK_TICK_MS = 5000;
/** Position drift beyond extrapolation that we treat as a seek. */
export const SEEK_EPSILON_S = 3;

const REMOTE_KINDS: ReadonlySet<string> = new Set([
  "play",
  "pause",
  "toggle",
  "next",
  "previous",
  "seekForward",
  "seekBackward",
]);

/**
 * Parse a "media-command" payload into a command. Pure and defensive: the
 * payload crossed an IPC boundary, so a shape we do not recognise returns
 * null instead of throwing inside an event handler.
 */
export const toRemoteCommand = (payload: unknown): DesktopRemoteCommand | null => {
  if (!payload || typeof payload !== "object") return null;
  const kind = (payload as { kind?: unknown }).kind;
  if (typeof kind !== "string") return null;
  if (kind === "seek") {
    const seconds = (payload as { seconds?: unknown }).seconds;
    if (typeof seconds !== "number" || !Number.isFinite(seconds)) return null;
    return { kind: "seek", seconds };
  }
  if (REMOTE_KINDS.has(kind)) return { kind } as DesktopRemoteCommand;
  return null;
};

/** What the bridge last told the platform, for change detection. */
export interface SentPlayback {
  songKey: string | null;
  playing: boolean;
  position: number;
  rate: number;
  wallMs: number;
}

export type PlaybackUpdateReason = "song" | "flip" | "seek" | "tick";

/**
 * Decide whether this store snapshot warrants an IPC round-trip. The store
 * updates position at 4 Hz; mirroring every tick over IPC would be noise, so
 * we send on song change, play/pause flip, a position jump the extrapolation
 * cannot explain (a seek), or a slow keep-honest tick while playing.
 */
export const playbackUpdateReason = (
  last: SentPlayback | null,
  songKey: string | null,
  state: { playing: boolean; position: number; rate: number },
  nowMs: number,
): PlaybackUpdateReason | null => {
  if (!last || last.songKey !== songKey) return "song";
  if (last.playing !== state.playing) return "flip";
  const elapsedS = (nowMs - last.wallMs) / 1000;
  const expected = last.playing ? last.position + elapsedS * last.rate : last.position;
  if (Math.abs(state.position - expected) > SEEK_EPSILON_S) return "seek";
  if (state.playing && nowMs - last.wallMs >= PLAYBACK_TICK_MS) return "tick";
  return null;
};
