/**
 * Guarded access to the Tauri globals (plano "uma so app" F5).
 *
 * The desktop shell (desktop/ in this repo) sets `withGlobalTauri: true`, so
 * inside the shell's webview `window.__TAURI__` carries the full API. We read
 * it from the global ON PURPOSE instead of importing `@tauri-apps/api`: the
 * app's package.json must not grow desktop-only dependencies (the ONLY place
 * allowed to declare them is desktop/package.json), and on every other
 * platform - native, plain browser - the global is simply absent and the
 * whole bridge no-ops.
 *
 * The shape below is a MINIMAL MIRROR of desktop/bindings.ts (generated by
 * tauri-specta). If a command or event changes on the Rust side, regenerate
 * the bindings (desktop/scripts/export-bindings.sh) and update this mirror -
 * the mirror is what keeps the app typechecking without the Tauri packages.
 */

interface TauriEventPayload {
  payload: unknown;
}

export interface TauriGlobals {
  core: {
    invoke: (command: string, args?: Record<string, unknown>) => Promise<unknown>;
  };
  event: {
    listen: (
      event: string,
      handler: (event: TauriEventPayload) => void,
    ) => Promise<() => void>;
  };
}

/** Narrow the untyped global without trusting it blindly. */
export const getTauriGlobals = (): TauriGlobals | null => {
  const candidate = (globalThis as { __TAURI__?: unknown }).__TAURI__;
  if (!candidate || typeof candidate !== "object") return null;
  const core = (candidate as { core?: { invoke?: unknown } }).core;
  const event = (candidate as { event?: { listen?: unknown } }).event;
  if (typeof core?.invoke !== "function" || typeof event?.listen !== "function") {
    return null;
  }
  return candidate as TauriGlobals;
};

/** True only inside the desktop shell's webview. */
export const isDesktopShell = (): boolean => getTauriGlobals() !== null;
