// GERADO por tauri-specta (desktop/scripts/export-bindings.sh). NAO editar a mao.
// O bridge da app (src/desktop/ em oms-music) mantem um espelho minimo destes
// tipos sobre window.__TAURI__; se este ficheiro mudar, o espelho muda tambem.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * O bridge chama isto por cada mudanca de musica (e limpa com None no fim da
 * fila / logout). Metadata fresca por musica, como o lockScreen.ts exige.
 */
async updateNowPlaying(nowPlaying: NowPlaying | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_now_playing", { nowPlaying }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Estado tocar/pausa + posicao. O bridge manda em flips de estado, saltos de
 * seek e num tick lento (5s) enquanto toca - a posicao autoritativa continua
 * do lado do player, isto e so o espelho para a UI da plataforma.
 */
async updatePlayback(playing: boolean, positionS: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_playback", { playing, positionS }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mostra/esconde; devolve o estado final (true = visivel) para a UI poder
 * reflectir sem segunda chamada.
 */
async miniplayerToggle() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("miniplayer_toggle") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Muda o preset, aplica ja se a janela existir, e persiste SEMPRE - e esta
 * persistencia que e a nossa melhoria sobre o Spotify.
 */
async miniplayerSetSize(size: MiniplayerSize) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("miniplayer_set_size", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preset persistido, para a UI arrancar com o selector certo.
 */
async miniplayerGetSize() : Promise<MiniplayerSize> {
    return await TAURI_INVOKE("miniplayer_get_size");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
mediaCommand: MediaCommand,
shellCommand: ShellCommand
}>({
mediaCommand: "media-command",
shellCommand: "shell-command"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Espelho 1:1 do RemoteCommand de src/player/lockScreen.ts. O serde emite
 * `{"kind":"play"}`, `{"kind":"seek","seconds":42}` etc.; qualquer renomeacao
 * aqui aparece no bindings.ts gerado e parte o typecheck do bridge em vez de
 * falhar em silencio.
 */
export type MediaCommand = { kind: "play" } | { kind: "pause" } | { kind: "toggle" } | { kind: "next" } | { kind: "previous" } | { kind: "seekForward" } | { kind: "seekBackward" } | { kind: "seek"; seconds: number }
/**
 * Os tres presets. Sem tamanho livre de proposito: um mini-player
 * redimensionavel a pixel acaba sempre numa forma que nenhum layout serve.
 */
export type MiniplayerSize = 
/**
 * Barra fina so com transporte.
 */
"bar" | 
/**
 * Rectangulo com artwork pequena + transporte.
 */
"rect" | 
/**
 * Quadrado com artwork grande.
 */
"square"
/**
 * Metadata que o bridge envia por cada mudanca de musica. Shape decalcado do
 * LockScreenMetadata da app (title/artist/albumTitle/artworkUrl) mais a
 * duracao, que o Now Playing quer para desenhar a barra de progresso.
 */
export type NowPlaying = { title: string; artist: string; albumTitle: string; artworkUrl: string | null; durationS: number | null }
/**
 * Accoes de shell que nao sao transporte: o bridge da app escuta este
 * evento e traduz em navegacao/UI (modo cinema, definicoes).
 */
export type ShellCommand = { type: "cinema" } | { type: "settings" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
